server:
  port: 8092

spring:
  application:
    name: payment-service

resilience4j:
  circuitbreaker:
    instances:
      paymentGateway:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
