spring.application.name=order-service
spring.config.import=optional:configserver:http://localhost:8888

# Fallback local port if config server is offline
server.port=8086

# Feign Client configuration
user-service.url=http://localhost:8085
