server.port=8080
spring.application.name=account-service
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
# Disable direct registration configuration details (or keep defaults to register client)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
