server.port=9090
spring.application.name=api-gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Enable discovery client locator routing
spring.cloud.gateway.discovery.locator.enabled=true
# Enable lowercase service name mapping (greet-service instead of GREET-SERVICE)
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
