server.port=8080

# Route 1: Example Org (Static)
spring.cloud.gateway.routes[0].id=example_route
spring.cloud.gateway.routes[0].uri=http://example.org
spring.cloud.gateway.routes[0].predicates[0]=Path=/example/**

# Route 2: Customer Service route with Rate Limiting and Path Rewriting
spring.cloud.gateway.routes[1].id=customer_route
spring.cloud.gateway.routes[1].uri=http://localhost:8089
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/customer/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/v1/customer/(?<segment>.*), /customers/$\{segment}
spring.cloud.gateway.routes[1].filters[1].name=RequestRateLimiter
spring.cloud.gateway.routes[1].filters[1].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.routes[1].filters[1].args.redis-rate-limiter.burstCapacity=20
spring.cloud.gateway.routes[1].filters[1].args.key-resolver=#{@userKeyResolver}

# Route 3: Billing Service route with Path Rewriting
spring.cloud.gateway.routes[2].id=billing_route
spring.cloud.gateway.routes[2].uri=http://localhost:8091
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/billing/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/v1/billing/(?<segment>.*), /billing/$\{segment}

# Resilience4j Config
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.failureRateThreshold=50
